spring:
  datasource:
    url: jdbc:oracle:thin:@13.124.220.79:1521:xe
    username: scott
    password : tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
logging:

  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
